spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: rootroot
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# REDIS 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
    timeout: 6000